### ISSUE TITLE
Loot table terraniatreehut refers to unknown item journey:darkterraniansoil

### ISSUE THREAD

**Issue by LemADEC** [TheSlayerMC/Journey-1.12#44]
As of 1.0.5.12, console is spammed for each world about a broken loot table:
```
[13:06:47] [Server thread/ERROR] [minecraft/LootTableManager]: Couldn't load loot table journey:chests/terraniatreehut from jar:file:/home/wheatnwitchery/_beta/./mods/Journey-Into-The-Light-1.12.2-1.0.5.12.jar!/assets/journey/loot_tables/chests/terraniatreehut.json
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'journey:darkterraniansoil'
>       at net.minecraft.util.JsonUtils.func_188172_b(SourceFile:124) ~[rc.class:?]
>       at net.minecraft.util.JsonUtils.func_188180_i(SourceFile:135) ~[rc.class:?]
>       at net.minecraft.world.storage.loot.LootEntryItem.func_186367_a(LootEntryItem.java:83) ~[bfp.class:?]
>       at net.minecraft.world.storage.loot.LootEntry$Serializer.deserialize(LootEntry.java:69) ~[bfr$a.class:?]
>       at net.minecraft.world.storage.loot.LootEntry$Serializer.deserialize(LootEntry.java:45) ~[bfr$a.class:?]
>       at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
>       at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[TypeAdapterRuntimeTypeWrapper.class:?]
>       at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[ArrayTypeAdapter.class:?]
>       at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
>       at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
>       at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
>       at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
>       at net.minecraft.util.JsonUtils.func_188174_a(SourceFile:447) ~[rc.class:?]
>       at net.minecraft.world.storage.loot.LootPool$Serializer.deserialize(LootPool.java:144) ~[bfq$a.class:?]
>       at net.minecraft.world.storage.loot.LootPool$Serializer.deserialize(LootPool.java:138) ~[bfq$a.class:?]
>       at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
>       at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[TypeAdapterRuntimeTypeWrapper.class:?]
>       at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[ArrayTypeAdapter.class:?]
>       at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
>       at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
>       at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
>       at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
>       at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
>       at net.minecraft.world.storage.loot.LootTable$Serializer.deserialize(LootTable.java:204) ~[bfs$a.class:?]
>       at net.minecraft.world.storage.loot.LootTable$Serializer.deserialize(LootTable.java:199) ~[bfs$a.class:?]
```

**Comment by AllShamNoWow101** [comment]
This has been fixed in newer versions
