### ISSUE TITLE
[Crash] Clients methods on server side.

### ISSUE THREAD

**Issue by BlesseNtumble** [TheSlayerMC/Journey-1.12#50]
```
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/particle/ParticleLava
	at net.journey.enums.EnumParticlesClasses.<clinit>(EnumParticlesClasses.java:10) ~[EnumParticlesClasses.class:?]
	at net.journey.blocks.tileentity.TileEntitySenterianAltar.spawnMob(TileEntitySenterianAltar.java:130) ~[TileEntitySenterianAltar.class:?]
	at net.journey.blocks.tileentity.TileEntitySenterianAltar.func_73660_a(TileEntitySenterianAltar.java:93) ~[TileEntitySenterianAltar.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2159) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:851) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:984) ~[MinecraftServer.class:?]
	... 4 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.ParticleLava
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241]
	at net.journey.enums.EnumParticlesClasses.<clinit>(EnumParticlesClasses.java:10) ~[EnumParticlesClasses.class:?]
	at net.journey.blocks.tileentity.TileEntitySenterianAltar.spawnMob(TileEntitySenterianAltar.java:130) ~[TileEntitySenterianAltar.class:?]
	at net.journey.blocks.tileentity.TileEntitySenterianAltar.func_73660_a(TileEntitySenterianAltar.java:93) ~[TileEntitySenterianAltar.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2159) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:851) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:984) ~[MinecraftServer.class:?]
	... 4 more
```

**Comment by Dizzlepop12** [comment]
Fixed in next update
