### ISSUE TITLE
1.12.2 Crash - Invalid Dim?

### ISSUE THREAD

**Issue by BaccarWozat** [TheSlayerMC/Journey-1.12#56]
> java.lang.IllegalArgumentException: Invalid dimension id 8
	at net.minecraft.world.DimensionType.func_186069_a(DimensionType.java:77)
	at net.journey.client.MusicTicker.getDimension(MusicTicker.java:56)

What I think happened was when the map was started, Journey knew which dimensions were originally reserved, but later on I started a Utility Worlds mining dimension (ID 8) and somehow Journey didn't recognize it.

I restarted the game and got the same crash, so is Journey keeping and reusing an internal list of dims?
Restarted without Journey and there was no crash.

1.12.2; Forge 2854; Journey 1.0.6.3, Utility Worlds 1.1.0.

[Crashlog](https://paste.ee/p/sLxQg)

**Comment by Dizzlepop12** [comment]
Can you try to create a new mining dimension with a different ID?

**Comment by BaccarWozat** [comment]
Utility Worlds, and some other mods as well, create dimensions through Forge reserving the next available dimension. I believe Forge chooses the number, so I could probably create 9 if 8 was created by something else first (Mystcraft possibly). But then 8 would still be there and generate the crash. I'll attempt it and report the results.

Or, are you asking me to create 9 in the existing test world which already has 8?

**Comment by Dizzlepop12** [comment]
I meant you should delete your config files, restart the game, and try a different dim ID. However, since it doesn't work that way, try deleting your config files and try again.

**Comment by BaccarWozat** [comment]
Deleted config files, but still crashed.
> [06:03:47] [Client thread/FATAL] [minecraft/Minecraft]: Unreported exception thrown!
java.lang.IllegalArgumentException: Invalid dimension id 8
	at net.minecraft.world.DimensionType.func_186069_a(DimensionType.java:77) ~[ayn.class:?]
        at net.journey.client.MusicTicker.getDimension(MusicTicker.java:56)
[Crashlog](https://paste.ee/p/kVUXO)

In all honesty, I hadn't changed anything in the original config, and I don't see anything in it that suggests Journey stores information in it that affects whether it can find dimensions created and reserved after the map was first started.
As the error is from MusicTicker, is the music important to playability? I usually have it turned off.

EDIT: I got the exact same crash error after walking into a Mystcraft world instead. Only major difference was it was lagging a bit (Mystcraft usually does).
Upon rejoining the game, I got out quickly, waited long enough to ensure there was no crash from being in the overworld, then started a UW mining world and crashed in DIM 9.

**Comment by ghost** [comment]
maruohon/justenoughdimensions#59

I had a similar issue here in Just Enough Dimensions, perhaps this might give a lead.
